<a href="https://colab.research.google.com/github/and00h/mlvm_labs/blob/main/Lab01_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print(np.__version__)

Numpy provides many functions to **create** arrays


In [ ]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     


**Slicing:** In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing.


In [ ]:
nums = list(range(5))     # range is a built-in function that creates a list of integers
nums = np.array(nums)     # convert python list to numpy array
print(nums)               # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(nums[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"
nums[2:4] = [8, 9]        # Create a new sub-array
print(nums)  
print(nums.shape) 


Let us see some examples of **Matrix** **multiplication**


In [ ]:
import time  # import module to calculate execution time


In [ ]:
x = np.array([1, 0.01, 0.5, 0.78])
w = np.array([1, 2, 3, -3])
b = 0.5

start_time = time.time()
y = np.dot(w, x) + b  # linear regression
end_time = time.time()
print(y)
print(y.shape)

vec_time = end_time-start_time
print("Execution time with vectorization {} seconds".format(vec_time))

The same result can be obtained with a less efficient for loop.

In [ ]:
start_time = time.time()
x_n = x.shape[0]
y = 0
for i in range(x_n):
   y += w[i]*x[i] + b
end_time = time.time()

print(y)
print(y.shape)

print("Execution time without vectorization {} seconds".format(end_time-start_time))
print(vec_time/(end_time-start_time))   # print the increase in execution time 
                                        # warning: for small vectors it varies a lot between runs!

The matmul function allow to multiply N-Dimensional arrays - the behaviour 



In [ ]:
a = np.random.random_sample(size=(5,3))  # generate random matrix with 5 rows and 3 columns
b = np.random.random_sample(size=(3,4))  # generate random matrix with 3 rows and 4 columns

print(a)
print(b)

c = np.matmul(a,b)
print(c)
print(c.shape)     # prints the shape of the resulting matrix, e.g. (5,4)


What happens if the inner dimensions are not compatible?


In [ ]:
print(np.matmul(b, a))

Let us see another example of how a vectorized implementation is more efficient!


In [ ]:
a = np.random.random_sample((5000,))    # generate a large vector

# vectorized calculation
start_time = time.time()
exp_a = np.exp(a)
end_time = time.time()
print("Execution time with vectorization {} seconds".format(end_time-start_time))

start_time = time.time()
x_n = a.shape[0]
exp_a = np.zeros(a.shape)
for i in range(x_n):
   exp_a[i] = np.exp(a[i])
end_time = time.time()
print("Execution time without vectorization {} seconds".format(end_time-start_time))


**Exercise 1**


Given the amount of Carbs, Proteins, Fats in 100g of different foods, 
knowing that carbs and proteins provides 4 calories and fats 9 calories,
calculate the % of calories from carbs, proteins and fats for each food


In [ ]:
grams = np.array([[ 27, 5.8, 41.5, 18.0 ], [ 0.7, 2.5, 8, 4 ],[ 0.2, 0.3, 1.2, 29.5 ]])
grams

In [ ]:
import numpy as np

grams = np.array([[ 27, 5.8, 41.5, 18.0 ], [ 0.7, 2.5, 8, 4 ],[ 0.2, 0.3, 1.2, 29.5 ]])
calories = np.array([[4] * 4, [4] * 4, [9] * 4])
calories_part = grams * calories

calories_vec = calories[:, 0:1]
calories_tot = np.transpose(np.matmul(np.transpose(grams), calories_vec))

calories_tot_matr = np.array([*calories_tot] * 3)
(calories_part / calories_tot_matr) * 100



array([[95.91474245, 64.62395543, 79.50191571, 20.36775106],
       [ 2.48667851, 27.8551532 , 15.3256705 ,  4.5261669 ],
       [ 1.59857904,  7.52089136,  5.17241379, 75.10608204]])

**Exercise 2**

Given two 1-D arrays **x** (real values) and **y** (discreet labels), and a constant parameter *m*, implement the following formula:

$z_i = \bigg \{ \begin{matrix} \parallel x_i \parallel ^ 2 \text{  if  } y_i =1 \\ \parallel m - x_i \parallel ^ 2 \text{  if  } y_i = 0 \end{matrix}$

In [ ]:
x = np.array([0.08444168, 0.5717077,  0.86764178, 0.2427889,  0.44898618, 0.23330771,
 0.14876752, 0.41267104, 0.38951113, 0.60130308])
print(x)
y = np.array([0, 0, 1, 1, 0, 0, 0, 1, 1, 0])
print(y)


In [ ]:
x = np.array([0.08444168, 0.5717077,  0.86764178, 0.2427889,  0.44898618, 0.23330771,
 0.14876752, 0.41267104, 0.38951113, 0.60130308])
print(x)
y = np.array([0, 0, 1, 1, 0, 0, 0, 1, 1, 0])
print(y)
m = 0.5
print(m)

y2 = (y - 1) + y
m_vec = ((y + 1) % 2) * m
(m_vec + (y2 * x)) ** 2


[0.08444168 0.5717077  0.86764178 0.2427889  0.44898618 0.23330771
 0.14876752 0.41267104 0.38951113 0.60130308]
[0 0 1 1 0 0 0 1 1 0]
0.5
[-1 -1  1  1 -1 -1 -1  1  1 -1]
[0.5 0.5 0.  0.  0.5 0.5 0.5 0.  0.  0.5]


array([0.17268872, 0.00514199, 0.75280226, 0.05894645, 0.00260241,
       0.07112478, 0.12336426, 0.17029739, 0.15171892, 0.01026231])

**Exercise 3**

Given a matrix x of size M by N, where M is the number of samples and N is the number of features, write a vectorized expression to perform min-max scaling:
𝑥′=  (𝑥  − min⁡(𝑥))/(max⁡(𝑥)−min⁡(𝑥))



In [ ]:
import numpy as np
import numpy.matlib

np.random.seed(123)

x = np.matlib.randn(4, 4)
print(x)
min_matr = np.ones(x.shape) * x.min()
print(min_matr)
max_matr = np.ones(x.shape) * x.max()
print(max_matr)
minmax_matr = max_matr - min_matr

(x - min_matr) / minmax_matr

[[-1.0856306   0.99734545  0.2829785  -1.50629471]
 [-0.57860025  1.65143654 -2.42667924 -0.42891263]
 [ 1.26593626 -0.8667404  -0.67888615 -0.09470897]
 [ 1.49138963 -0.638902   -0.44398196 -0.43435128]]
[[-2.42667924 -2.42667924 -2.42667924 -2.42667924]
 [-2.42667924 -2.42667924 -2.42667924 -2.42667924]
 [-2.42667924 -2.42667924 -2.42667924 -2.42667924]
 [-2.42667924 -2.42667924 -2.42667924 -2.42667924]]
[[1.65143654 1.65143654 1.65143654 1.65143654]
 [1.65143654 1.65143654 1.65143654 1.65143654]
 [1.65143654 1.65143654 1.65143654 1.65143654]
 [1.65143654 1.65143654 1.65143654 1.65143654]]


matrix([[0.32884026, 0.83960948, 0.66443865, 0.22568867],
        [0.45316982, 1.        , 0.        , 0.48987491],
        [0.90547098, 0.3825146 , 0.42857859, 0.57182542],
        [0.96075469, 0.43838315, 0.48617974, 0.4885413 ]])

**Exercise 4**


Given a 1D array, calculate the average of each consecutive triplet


In [ ]:
x = np.array([1, 3, 5, 10, 15, 12, 23, 5, 6])

sums = np.convolve(x, np.ones(3), 'valid')
sums / 3

array([ 3.        ,  6.        , 10.        , 12.33333333, 16.66666667,
       13.33333333, 11.33333333])